name: deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: cache node modules
        uses: actions/cache@v2.1.7
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-build-${{ env.cache-name }}-${{ runner.OS }}-build-${{ runner.OS }}-

      - name: install yarn
        run: npm install yarn -g

      - name: install packages
        run: yarn install --frozen-lockfile

      - name: build
        run: yarn build

      - name: gitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.GH_PAGES_SECRET }}
          publish_branch: gh-pages
          publish_dir: build
          destination_dir: .
          keep_files: false
          force_orphan: false
          enable_jekyll: true
